jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Fetch contributions (GraphQL)
        run: |
          echo '{"query":"{ user(login: \"Shubham-168\") { contributionsCollection { contributionCalendar { totalContributions weeks { contributionDays { color contributionCount date } } } } } }"}' > query.json
          curl -s -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -X POST https://api.github.com/graphql -d @query.json \
            > public/data/github-stats.json

      - name: Fetch repos (REST)
        run: |
          curl -s "https://api.github.com/users/Shubham-168/repos?per_page=100" \
            > public/data/repos.json

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/github-stats.json public/data/repos.json
          git diff --quiet --exit-code || git commit -m "chore: update GitHub stats"
          git push origin HEAD:main
